name: dart_minecraft
description: Brings Minecraft and Mojang APIs to Dart.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4

# analyzer:
#   - enable-experiment:
#     - non-nullable
