name: dart_minecraft
description: Utilities for Minecraft and Mojang Web-APIs and reading/writing NBT Files. 
version: 0.5.1
homepage: https://github.com/spnda/dart_minecraft
repository: https://github.com/spnda/dart_minecraft
issue_tracker: https://github.com/spnda/dart_minecraft/issues

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  uuid: ^3.0.6
  collection: ^1.16.0
  http: ^0.13.4
  path: ^1.8.1
dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1

# analyzer:
#   - enable-experiment:
#     - non-nullable
